version: 2.1
description: FaunaDB Go Driver Tests

executors:
  core:
    parameters:
      go_version:
        type: string
      version:
        type: enum
        enum: ["release", "nightly"]
    resource_class: large
    docker:
      - image: circleci/golang:<<parameters.go_version>>

      - image: gcr.io/faunadb-cloud/faunadb/enterprise/<<parameters.version>>:latest
        name: core
        auth:
          username: _json_key
          password: $GCR_KEY

    environment:
      FAUNA_ROOT_KEY: secret
      FAUNA_ENDPOINT: http://core:8443

commands:
  build_and_test:
    description: "Run Go tests"
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-deps-{{ checksum "go.sum" }}

      - run:
          name: Install dependencies
          command: go mod download

      - run: go get github.com/jstemmer/go-junit-report

      - save_cache:
          paths:
          - /go/pkg
          key: v1-deps-{{ checksum "go.sum" }}

      - run:
          name: Run Tests
          command: |
            cd v2
            mkdir results
            go test -v -race -coverprofile=results/coverage.txt -covermode=atomic ./... 2>&1 | tee log.txt

      - run:
          name: Gather Results
          when: always
          command: |
            cd v2
            mkdir -p results/junit
            go-junit-report -package-name faunadb -set-exit-code < log.txt > results/junit/report.xml

      - store_test_results:
          path: results/

jobs:
  core-stable-1-13:
    executor:
      name: core
      go_version: "1.13"
      version: release
    steps:
      - build_and_test

  core-nightly-1-13:
    executor:
      name: core
      go_version: "1.13"
      version: nightly
    steps:
      - build_and_test

  core-stable-1-12:
    executor:
      name: core
      go_version: "1.12"
      version: release
    steps:
      - build_and_test

  core-nightly-1-12:
    executor:
      name: core
      go_version: "1.12"
      version: nightly
    steps:
      - build_and_test

  core-stable-1-11:
    executor:
      name: core
      go_version: "1.11"
      version: release
    steps:
      - build_and_test

  core-nightly-1-11:
    executor:
      name: core
      go_version: "1.11"
      version: nightly
    steps:
      - build_and_test

workflows:
  version: 2
  build_and_test:
    jobs:
      - core-stable-1-13:
          context: faunadb-drivers
      - core-nightly-1-13:
          context: faunadb-drivers
      - core-stable-1-12:
          context: faunadb-drivers
      - core-nightly-1-12:
          context: faunadb-drivers
      - core-stable-1-11:
          context: faunadb-drivers
      - core-nightly-1-11:
          context: faunadb-drivers
